# Permalinks
permalink:      /:title

# Setup
title:          Jack Colley
paginate:       5
baseurl:        ""
url:            "https://jackcolley.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jack Colley
  url:          http://jackcolley.co.uk
  email:        jack@jackcolley.co.uk

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
